// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqitjhaotpautjywoeys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaXRqaGFvdHBhdXRqeXdvZXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NzE3MTIsImV4cCI6MjA4MTE0NzcxMn0.CS8QpR9kVzHC6jGnkwV3onm-HiVNWyxF8rryfK2p87o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});